--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/kostamax27/Hypixel-Bow
build-by-default: true
branches:
  - main
  - pm5
  - legacy/pm4
projects:
  Hypixel-Bow:
    path: ""
    icon: "Hypixel-Bow.gif"
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.1.3
    lint:
      phpstan: false
...
