--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/kostamax27/Hypixel-Bow
build-by-default: true
branches:
- main
projects:
  Hypixel-Bow:
    path: ""
    icon: "Hypixel-Bow.gif"
    libs:
      - src: Frago9876543210\EasyForms\EasyForms
        version: ^1.5.0
    lint:
        phpstan: false
...
