--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/kostamax27/Hypixel-Bow
build-by-default: true
branches:
- main
projects:
  Hypixel-Bow:
    path: ""
    icon: "Hypixel-Bow.gif"
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.0.0
    lint:
        phpstan: false
...
