---
name: HypixelBow
api: 5.0.0
main: kostamax27\HypixelBow\HypixelBow
version: 1.1.6
author: kostamax27
mcpe-protocol:
  - 486
  - 503
  - 527
  - 534
  - 544
  - 545
  - 554
  - 557
  - 560
  - 567
  - 575
  - 582

virions:
  - FormsUI

permissions:
  hypixelbow.cmd:
    default: op
...
